# Generated by Django 4.0.1 on 2022-01-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subHeader', models.TextField(max_length=200, verbose_name='Texto descriptivo Header')),
                ('headImg1', models.ImageField(upload_to='uploads/', verbose_name='Imagen Banner 1')),
                ('headImg2', models.ImageField(upload_to='uploads/', verbose_name='Imagen Banner 1')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-created'],
            },
        ),
    ]
