# Generated by Django 4.0.1 on 2022-01-27 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nombre grupo del grupo de imgs', help_text="tip: Poner nombre relacionado al servico. Ej... 'Imgs_Social'.", max_length=200, verbose_name='Título')),
                ('headImg1', models.ImageField(upload_to='uploads/', verbose_name='Imagen Banner 1')),
                ('headImg2', models.ImageField(upload_to='uploads/', verbose_name='Imagen Banner 2')),
                ('headImg3', models.ImageField(upload_to='uploads/', verbose_name='Imagen Banner 3')),
                ('destacada1', models.ImageField(upload_to='eventos/destacados/', verbose_name='Evento destacado 1')),
                ('destacada2', models.ImageField(upload_to='eventos/destacados/', verbose_name='Evento destacado 2')),
                ('destacada3', models.ImageField(upload_to='eventos/destacados/', verbose_name='Evento destacado 3')),
                ('destacada4', models.ImageField(upload_to='eventos/destacados/', verbose_name='Evento destacado 4')),
                ('destacada5', models.ImageField(upload_to='eventos/destacados/', verbose_name='Evento destacado 5')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='headImg1',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='headImg2',
        ),
        migrations.AlterField(
            model_name='servicios',
            name='subHeader',
            field=models.TextField(max_length=60, verbose_name='Texto descriptivo Header'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='imagenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='img_service', to='core.imagenes', verbose_name='Imágenes'),
        ),
    ]
