# Generated by Django 4.0.1 on 2022-02-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_imagenes_options_alter_servicios_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='subHeader_destacada1',
            field=models.TextField(default='', help_text='Breve descripción, max. 200 caracteres.', max_length=200, verbose_name='Texto descriptivo Header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenes',
            name='subHeader_destacada2',
            field=models.TextField(default='', help_text='Breve descripción, max. 200 caracteres.', max_length=200, verbose_name='Texto descriptivo Header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenes',
            name='subHeader_destacada3',
            field=models.TextField(default='', help_text='Breve descripción, max. 200 caracteres.', max_length=200, verbose_name='Texto descriptivo Header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenes',
            name='subHeader_destacada4',
            field=models.TextField(default='', help_text='Breve descripción, max. 200 caracteres.', max_length=200, verbose_name='Texto descriptivo Header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenes',
            name='subHeader_destacada5',
            field=models.TextField(default='', help_text='Breve descripción, max. 200 caracteres.', max_length=200, verbose_name='Texto descriptivo Header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenes',
            name='titulo_destacada1',
            field=models.CharField(default='', help_text='Título para Imagen destacada', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenes',
            name='titulo_destacada2',
            field=models.CharField(default='', help_text='Título para Imagen destacada', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenes',
            name='titulo_destacada3',
            field=models.CharField(default='', help_text='Título para Imagen destacada', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenes',
            name='titulo_destacada4',
            field=models.CharField(default='', help_text='Título para Imagen destacada', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenes',
            name='titulo_destacada5',
            field=models.CharField(default='', help_text='Título para Imagen destacada', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
