# Generated by Django 4.0.1 on 2022-02-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_portafolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='imagen',
            field=models.ImageField(default='', upload_to='portafolio/', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
