# Generated by Django 4.0.1 on 2022-02-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_portafolio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Título')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolio',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='portafolio',
            name='categoria',
            field=models.ManyToManyField(help_text='Seleccione una o varias categorías relacionadas al item.', to='core.Categorias', verbose_name='Imagen'),
        ),
    ]
