# Generated by Django 4.0.1 on 2022-02-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categorias_portafolio_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['-created'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='categoria',
            field=models.ManyToManyField(help_text='Seleccione una o varias categorías relacionadas al item.', to='core.Categorias', verbose_name='Categorías'),
        ),
        migrations.RemoveField(
            model_name='portafolio',
            name='clase',
        ),
        migrations.AddField(
            model_name='portafolio',
            name='clase',
            field=models.ManyToManyField(help_text='Seleccione una o las dos clases de servicio.', to='core.Servicios', verbose_name='Servicio'),
        ),
    ]
