# Generated by Django 4.0.1 on 2022-02-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_categorias_options_alter_portafolio_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='clase',
            field=models.ManyToManyField(help_text='Seleccione una o las dos clases de servicio.', to='core.Servicios', verbose_name='Servicio relacionado'),
        ),
    ]
