# Generated by Django 4.0.1 on 2022-02-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_portafolio_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Tipo')),
                ('precio', models.CharField(max_length=200, verbose_name='Precio')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Breve descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imágenes',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['-created'],
            },
        ),
    ]
