# Generated by Django 4.0.1 on 2022-02-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paquetes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paquetes',
            options={'ordering': ['-created'], 'verbose_name': 'Paquete', 'verbose_name_plural': 'Paquetes'},
        ),
        migrations.AlterField(
            model_name='paquetes',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='Breve descripción'),
        ),
    ]
