# Generated by Django 4.0.1 on 2022-02-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_paquetes_options_alter_paquetes_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Breve descripción')),
                ('imagen', models.ImageField(upload_to='marvImgs/galeria/', verbose_name='Imagen Banner 1')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Galería',
                'verbose_name_plural': 'Galería',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='destacada2',
            field=models.ImageField(upload_to='marvImgs/eventos/destacados/', verbose_name='Evento destacado 2'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='destacada3',
            field=models.ImageField(upload_to='marvImgs/eventos/destacados/', verbose_name='Evento destacado 3'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='destacada4',
            field=models.ImageField(upload_to='marvImgs/eventos/destacados/', verbose_name='Evento destacado 4'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='destacada5',
            field=models.ImageField(upload_to='marvImgs/eventos/destacados/', verbose_name='Evento destacado 5'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='headImg1',
            field=models.ImageField(upload_to='marvImgs/uploads/', verbose_name='Imagen Banner 1'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='headImg2',
            field=models.ImageField(upload_to='marvImgs/uploads/', verbose_name='Imagen Banner 2'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='headImg3',
            field=models.ImageField(upload_to='marvImgs/uploads/', verbose_name='Imagen Banner 3'),
        ),
        migrations.AlterField(
            model_name='paquetes',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='imagen',
            field=models.ImageField(upload_to='marvImgs/portafolio/', verbose_name='Imagen'),
        ),
    ]
