# Generated by Django 4.0.1 on 2022-02-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_galeria_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
