# Generated by Django 4.0.1 on 2022-02-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_galeria_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200, verbose_name='Pregunta')),
                ('respuesta', models.TextField(max_length=200, verbose_name=' Respuesta')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('clase', models.ManyToManyField(help_text='Seleccione una o las dos clases de servicio.', to='core.Servicios', verbose_name='Servicio relacionado')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'ordering': ['-created'],
            },
        ),
    ]
