# Generated by Django 4.0.1 on 2022-02-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Número de Celular')),
                ('facebook', models.URLField(verbose_name='FaceBook')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contacto',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'ordering': ['-created'], 'verbose_name': 'Faq', 'verbose_name_plural': 'Faqs'},
        ),
    ]
