# Generated by Django 4.0.1 on 2022-03-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_portafolio_cat_eventos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='cat_eventos',
            field=models.ManyToManyField(blank=True, help_text='Seleccione una o varios eventos relacionadas al item.', null=True, to='core.CatEventos', verbose_name='Eventos'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='categoria',
            field=models.ManyToManyField(blank=True, help_text='Seleccione una o varias categorías relacionadas al item.', null=True, to='core.Categorias', verbose_name='Categorías'),
        ),
    ]
