# Generated by Django 4.0.1 on 2022-03-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_portafolio_cat_eventos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatPaquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Título')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Tipo de Eventos',
                'verbose_name_plural': 'Tipo de Eventos',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='paquetes',
            name='cat_paquete',
            field=models.ManyToManyField(blank=True, help_text='Seleccione una o varias categorías relacionadas al item.', null=True, to='core.CatPaquetes', verbose_name='Categorías'),
        ),
    ]
