# Generated by Django 4.0.1 on 2022-03-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_catpaquetes_paquetes_cat_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetes',
            name='cat_eventos',
            field=models.ManyToManyField(blank=True, help_text='Seleccione una o varios eventos relacionadas al item.', null=True, to='core.CatEventos', verbose_name='Eventos'),
        ),
    ]
