# Generated by Django 4.0.1 on 2022-03-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_paquetes_cat_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetes',
            name='caracteristicas',
            field=models.TextField(default='', max_length=200, verbose_name='Breve descripción'),
            preserve_default=False,
        ),
    ]
