# Generated by Django 4.0.1 on 2022-03-23 18:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_paquetes_caracteristicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetes',
            name='caracteristicas',
            field=models.TextField(max_length=600, verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='paquetes',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Breve descripción'),
        ),
    ]
