# Generated by Django 4.0.1 on 2022-03-23 18:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_paquetes_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetes',
            name='caracteristicas',
            field=ckeditor.fields.RichTextField(verbose_name='Características'),
        ),
    ]
