# Generated by Django 4.0.1 on 2022-03-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre del cliente')),
                ('user_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('paquete', models.CharField(max_length=60, verbose_name='Nombre de la compra')),
                ('cantidad', models.IntegerField(verbose_name='Valor')),
                ('payment_mercado_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Id del movimeinto en mercado pago')),
                ('payment_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Status del pago')),
                ('payment_type', models.CharField(blank=True, max_length=18, null=True, verbose_name='Tipo de pago')),
                ('merchant_order_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='merchant_order_id')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Pagos',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
